<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_magnificpopup_hookexamples"
 *
 * Auto generated by Extension Builder 2014-09-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Magnific Popup - Hook Examples',
	'description' => 'This extension provides some working examples for hooks in EXT:jh_magnificpopup. Please see documentatio,n documentation of EXT:jh_magnificpopup (Chapter Development) and have a look at the commented code of this extension.',
	'category' => 'doc',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => false,
	'createDirs' => '',
	'clearCacheOnLoad' => false,
	'version' => '0.3.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
			'jh_magnificpopup' => '0.3.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);